server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.tyshawn.entity
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  application:
    name: springclouddemo-provider-book
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://114.55.27.138:3306/tyshawn_test
    username: root
    password: Root!!2019
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

#客户端注册进eureka服务列表内
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka, http://localhost:7002/eureka
  instance:
    instance-id: springclouddemo-provider-book-8001
    prefer-ip-address: true                                 #访问路径可以显示IP地址

info:
  app.name: springclouddemo
  company.name: www.tyshawn.com
  build.artifact: $project.artifactId$
  build.version: $project.version$