server:
  port: 9527

spring:
  application:
    name: springclouddemo-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka, http://localhost:7002/eureka
  instance:
    instance-id: springclouddemo-zuul-gateway-9527
    prefer-ip-address: true

zuul:
  prefix: /yezi
  ignored-services: "*"

info:
  app.name: springclouddemo
  company.name: www.com.tyshawn.com
  build.artifact: $project.artifactId$
  build.version: $project.version$